# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20190902_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 14, 15, 27, 577000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='sample.png', upload_to='blog/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 14, 15, 27, 576000, tzinfo=utc)),
        ),
    ]
