# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20190902_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 9, 53, 48, 206000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 9, 53, 48, 205000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='question',
            field=models.TextField(),
        ),
    ]
